In [1]:
from graph import PrepareData
from graph import FeatureExtractor

p = PrepareData(path=r"G:\Deepesh's Data\Graph-Library\input\sample.csv",
    graph_type="directed", test_size=0.2, n_jobs=4)

X_train, X_test, y_train, y_test = p.prepare()
# df_pos, df_neg = p.prepare()
# data = p.read_graph()

Creating graph, It may take some time.

100%|██████████| 50000/50000 [00:00<00:00, 806451.14it/s]

In [9]:
import pandas as pd
pd.concat((X_train, y_train), axis=1)

          source_node  destination_node  label
0              373687            490608      1
1              238610            339927      1
2             1852465             61534      1
3              304979           1182914      1
4             1006847            890595      1
...               ...               ...    ...
15100027      1042510            235789      0
15100028      1145383           1280657      0
15100029        10769            259124      0
15100030      1701772           1797573      0
15100031       438324           1019169      0

[15100032 rows x 3 columns]

In [10]:
X_train

          source_node  destination_node
0              373687            490608
1              238610            339927
2             1852465             61534
3              304979           1182914
4             1006847            890595
...               ...               ...
15100027      1042510            235789
15100028      1145383           1280657
15100029        10769            259124
15100030      1701772           1797573
15100031       438324           1019169

[15100032 rows x 2 columns]

In [2]:
# from graph import FeatureExtractor

fex = FeatureExtractor(graph_type='directed')
fex.fit(X_train, y_train)

In [3]:
X_train.columns = ['source', 'destination']
X_train

        source  destination
0         2487       933067
1         8585       774230
2         1372      1533594
3         5408       452331
4         6948      1727505
...        ...          ...
79996  1080678       219659
79997   965097       341239
79998   678888      1440649
79999   701931       834604
80000  1339626      1822082

[80001 rows x 2 columns]

In [4]:
data = fex.transform(X_train)

In [9]:
fex.graph.successors(2272)

NetworkXError: The node 2272 is not in the digraph.

In [6]:
data

,source,destination,num_successors_source,num_predecessors_source,num_successors_destination,num_predecessors_destination,back_link
0,2487,933067,0,0,0,0,0
1,8585,774230,0,0,0,0,0
2,1372,1533594,0,0,0,0,0
3,5408,452331,0,0,0,0,0
4,6948,1727505,0,0,0,0,0
...,...,...,...,...,...,...,...
79996,1080678,219659,0,0,0,0,0
79997,965097,341239,0,0,0,0,0
79998,678888,1440649,0,0,0,0,0
79999,701931,834604,0,0,0,0,0
80000,1339626,1822082,0,0,0,0,0

In [26]:
pd.read_csv('./input/train_csv.csv')[:50000].to_csv('./input/sample.csv', index=)